'use client'
import './globals.css'
import { ChakraProvider } from '@chakra-ui/react'

// export const metadata = {
//   title: 'PIAIC',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ChakraProvider>
        {children}
        </ChakraProvider></body>
    </html>
  )
}
